### PR TITLE
Library updates, method updates, and faster opening.

### PR DESCRIPTION
**Pull request by ppkantorski**
Updated libnx (won't be reflected here, but I've pulled the lastest libnx from their repository and compiled it)
Now utilizing `libultrahand v1.7.8` (expanded `libtesla` & `libultra`).
Custom wallpaper / theme support.
Users can override the system wallpaper / theme with `sdmc:/config/edizon/wallpaper.rgba` and `sdmc:/config/edizon/theme.ini`.
Faster opening / game detection.
Fix for local IP calls.
Temperature readings are now done through i2c.

Feel free to modify this to your liking, this was just the fork I was playing with.  If you have any thoughts, comments, questions or concerns feel free to let me know.

### CODE REVIEW

**Comment by ppkantorski** [comment]
I've updated the libraries a bit to make things easier for devs.  I'll let you know when I'm able to link the updated libultrahand to this PR / fork.

**Comment by proferabg** [comment]
Will build this today and test. Was affected by the hurricane and trying to get back to normalcy.

**Comment by ppkantorski** [comment]
Alright the libraries have been cleaned up a bit more and relinked.  Feel free to check it out.

**Comment by ppkantorski** [comment]
Things should be pretty stable now.  I've even included a new directive `NO_FSTREAM_DIRECTIVE` for smaller compilation of this project.  Do let me know when you are able to test it out.

**Comment by proferabg** [comment]
Sorry that it took so long to get merged. I had to test on at least the past 2 major releases to make sure that nothing has broken with the big changes. Thanks again for your contributions, I put a thank you note on the releases page!

**Pull request merged**
